### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by vr8hub** [robinwhittleton/sigfrid-siwertz_downstream_macmillan-of-canada#1]
- [ ] Should "big grownup lady" in 1-5 be grown-up, since it's an adjective?
- [ ] Modernize spelling changes under-class to underclass in 1-9, which appears to be correct?
- [ ] Both _vira_ and _camphio_ appear to be Swedish card games, but you have the language as Northern Sami (se). Did you mean to make them Swedish (sv), or did you determine they really were Northern Sami? (In which case I'm dying to know how you figured that out.)
- [ ] There was a discussion about crepe/crape/crêpe sometime back (by coincidence also in one of your books). In that one, you chose crepe since it was the primary in M-W and crêpe was just a variant. I don't have a strong opinion here, but I usually go with the primary of a word if both the primary and variant are used (if they _consistently_ use the variant, I'll typically keep it). This is obviously a gray area, so keeping it crêpe is obviously OK, too.
- [ ] And in another gray area, the two ignored lint errors on the blockquotes are caused by unnecessary quotemarks. Unnecessary in that no one is reading the signs/whatever out loud, so they're superfluous. I usually remove them in such a situation. (Interestingly, they didn't use quotes on the letter in 2-6, which is another area I regularly see superfluous quotemarks.) Again, no strong feelings one way or the other, so up to your discretion.
- [ ] I never have cause to use flex; does it need a fallback if it's not supported, as we do with the dedication CSS?
- [ ] In a completely unasked for and therefore unnecessary opinion, cropping the oar that short on the cover looks a bit odd to me (love the picture, though). Leaving it entire and cutting off most of the dock/pier behind the woman looks … better (to me)? (Merely an unsolicited opinion, not binding in any way.)

**Comment by robinwhittleton** [comment]
Thanks for the detailed review! Points in order:

1. It’s “grown-up” already (https://github.com/robinwhittleton/sigfrid-siwertz_downstream_macmillan-of-canada/blob/main/src/epub/text/chapter-1-5.xhtml#L64). I guess you ran modernize-spelling before?
2. I left this as “under-class” as that felt more like an adjective vs ”underclass” as a noun. I can’t find any source that differentiates this though, so modernised in https://github.com/robinwhittleton/sigfrid-siwertz_downstream_macmillan-of-canada/commit/f69fd039c543ce5eb0491d177a9b2bfe457ee43b.
3. I have literally no excuse since I live in Sweden 🤦‍♂️ Fixed in https://github.com/robinwhittleton/sigfrid-siwertz_downstream_macmillan-of-canada/commit/0e0dd559bf1792c6082ebb0b3fd14bd06944964b.
4. You’ve got a better memory than me 🙂 crêpe -> crepe in https://github.com/robinwhittleton/sigfrid-siwertz_downstream_macmillan-of-canada/commit/d698d17a0faff55145b995b8caafaff868183016.
5. I’ll leave this as is I think.
6. All that flexbox declaration does is space the two items out to either side. The fallback is that there’s a normal space, which also looks fine.
7. I tried out a wider crop, but flicking backwards and forwards I think on balance I prefer the original crop as it centres the focus on the people more than the surroundings, which is definitely in keeping with the theme of the book.
